### ISSUE TITLE
Classes with java.util.Date don't generate

### ISSUE THREAD

**Issue by apkelly** [mattlogan/auto-value-firebase#5] opened 2016-10-10 14:47 UTC
A auto value attribute defined as this....
    public abstract Date startTime();

Generates this...
    private AutoValue_Date.FirebaseValue startTime;

Which according to Android Studio 2.2.1 isn't valid.

**Comment by mattlogan** [comment] 2016-11-03 18:45
Hey Andrew, sorry I missed this.

As far as I know, `java.util.Date` isn't supported by Firebase Database to begin with. This extension doesn't add any extra serialization/deserialization functionality to Firebase.

My advice would be to just save it as a `Long`, then add an extra getter method on the AutoValue class to convert from `Long` to `Date`.

**Comment by apkelly** [comment] 2016-11-03 23:23
Hi Matt, 

I just noticed that my code in AppEngine when storing/retrieving dates performs a conversion for Dates to long as you suggest. Any chance your extension could do the same, it seems like a common use-case and it'd mean developers wouldn't need an extra attribute.

If you're not keen to perform the extra step in the de/serialisation then happy for you to close this issue.

Thanks,

Andy.

**Comment by mattlogan** [comment] 2016-11-04 16:59
Yeah, I agree on its usefulness!

This issue is pretty close to being a duplicate of https://github.com/mattlogan/auto-value-firebase/issues/2, so I'll close this for now.

I don't have any immediate plans to add this but I'm certainly not against it. Perhaps in a few weeks.

**Closed as completed by mattlogan** 2016-11-04 16:59 UTC
